### ISSUE TITLE
Faster decompression (inflate)

### ISSUE THREAD

**Issue by photopea** [nodeca/pako#105]
Hi, I know that you have optimized your library a lot.

But is there any chance to make the decompression (inflate) faster? I use it for decoding PNG images with [UPNG.js](https://github.com/photopea/UPNG.js) (which calls pako.js) .  For large PNG files, it takes quite a lot of time (about 50% of time takes PNG filtering and 50% takes Inflate).

I attach one of my PNG images.
https://user-images.githubusercontent.com/15955558/28381646-e8566a36-6cbb-11e7-8d32-0d0f6ffe08a8.png

**Comment by puzrin** [comment]
According to benchmark, speed is comparable to native implementation. So, there is nothing to optimize more.

**Comment by photopea** [comment]
So pako.js is just some specific C implementation, rewritten to JS?  Is it the fastest existing C implementation, which you rewrote?

**Comment by puzrin** [comment]
@photopea there is only one and standard implementation, zlib. Everything possible is already optimized.

Also, it's impossible to find out something constructive until you have estimate what speed do you need to have. Current inflate speed in JS is > 50mb/sec, and i don't beleive you need better, because your sample is only 6mb size (0.1sec to decompress)

**Comment by photopea** [comment]
My 6 MB sample becomes 72 MB after decompression. Inflate takes over 0.5 second, so I thougt that 0.3 second would be great. But I guess you are right, it is already quite fast.

**Comment by puzrin** [comment]
50mb/sec is for the input (worst estimate, can be 80, 100, ...). Output can be of any size.

**Comment by puzrin** [comment]
Your slowdown can be in outer wrapper. To know exactly - benchmark of each stage should be done. Pako already has benchmark for node, but i think it's not a big problem adapt it for browser and result should not be worse.

**Comment by desudesutalk** [comment]
> there is only one and standard implementation, zlib.

There is at least [CloudFlare optimized version](https://www.snellman.net/blog/archive/2015-06-05-updated-zlib-benchmarks/) which is two times faster. But I don't think this optimizations can be applied to JS version. At least until SIMD.

@photopea If you really need speed, then take a look at [Native Client](https://developer.chrome.com/native-client). If it is not available, you can fall back to pako.

**Comment by photopea** [comment]
I measured the time of the single pako.inflate() call for my data.

My data is 6.376.520 B  and it takes  890 ms to inflate. So the process speed is  7.15 MB/s

I don't think it makes any sense to say 50MB/sec , it depends a lot on properties of data. If  1 MB should become 1 GB after inflating, it probably won't take 0.02 sec.  Or do you mean megabits, not megabytes?

**Comment by puzrin** [comment]
> There is at least CloudFlare optimized version which is two times faster

Those opts are for deflate only

**Comment by desudesutalk** [comment]
> My data is 6.376.520 B and it takes 890 ms to inflate.

Can you share your test data and test scripts? Because I just benchmarked pako in Chrome 59 and I got 30.4MB/s. Your sample in my browser should be inflated in 200ms.

> pako speed is only ~ 1.3 slower than plain C implementation

I just checked how you benchmark zlib. It is unfair! While pako just get typed array and in sync manner spits out another typed array, you make zlib work in async with all that `on data` stuff and buffers concatenations.

I corrected your benchmark and executed it with node v8.1.3

```
Selected samples: (1 of 1)
 > 1mb

Sample: 1mb.json (1048576 bytes raw / ~220828 bytes compressed)
 > deflate-imaya x 5.53 ops/sec ±1.77% (17 runs sampled)
 > deflate-pako x 11.09 ops/sec ±0.21% (30 runs sampled)
 > deflate-pako-string x 9.53 ops/sec ±0.52% (27 runs sampled)
 > deflate-pako-untyped x 6.31 ops/sec ±0.86% (19 runs sampled)
 > deflate-zlib x 18.05 ops/sec ±0.22% (47 runs sampled)
 > inflate-imaya x 103 ops/sec ±2.19% (67 runs sampled)
 > inflate-pako x 127 ops/sec ±2.15% (72 runs sampled)
 > inflate-pako-string x 60.23 ops/sec ±1.48% (59 runs sampled)
 > inflate-pako-untyped x 54.67 ops/sec ±1.14% (64 runs sampled)
 > inflate-zlib x 309 ops/sec ±2.31% (78 runs sampled)
```

So it is ~2 times slower. And for inflate it is ~2.4 times slower.

**Comment by puzrin** [comment]
> Can you share your test data and test scripts? 

https://github.com/nodeca/pako/tree/master/benchmark - everything is published

If you have improvements for benchmark - PR welcome. Be accurate about benchmarks please. If you demonstrate changes - it's better to make those reproducible. That means, show code diffs and results before and after change.

**Comment by desudesutalk** [comment]
@puzrin sorry, first comment was for @photopea, I just want to see his code and benchmark it by myself. I don't think his hardware is 4 times slower than mine.

Ok, I will make PR right now with my changes in benchmarks.

**Comment by photopea** [comment]
Here is my binary data, that need to be inflated. pako.inflate  takes 890 ms on my laptop in the Chrome browser.
[data.txt](https://github.com/nodeca/pako/files/1160510/data.txt)

**Comment by desudesutalk** [comment]
@photopea now I see. In browser I was using `inflateRaw` and looks like it is faster because check sum is not calculated (I think).  I retested with plain `inflate` and got 450ms for your data.

If you on laptop then this results seems accurate. I don't think you can get any faster than that.

By the way, why you not use `canvas` in browser for decoding? For png files you will get exact pixels values with [`getImageData`](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/getImageData)

**Comment by photopea** [comment]
@desudesutalk  When I call inflateRaw, I get "Uncaught invalid stored block lengths".

Do you mean loading an image thorough <img> element, drawing it into canvas, and then calling getImageData? I doubt it would be any faster. It would definitely need more memory. I load all files as binary and doing it through DOM would be very messy.

**Comment by desudesutalk** [comment]
@photopea to use `inflateRaw` you need to do a bit more with png file, skip checksum I think. But I don't know how to do it correctly. You need to read png specs for answer.

About canvas variant I think what it is better to test it. You don't need to put `canvas` into DOM to use it for pixels extraction. Maybe it will be faster because native png lib will be used.

**Comment by puzrin** [comment]
Canvas is convenient in most of cases. It's disadvantage is, that it supports only 8 bits per channel, without access to gamma and color profile. Is it significant or not - depends on use case.

Drop adler crc from inflate process should give ~30% of difference.

**Comment by photopea** [comment]
I understand PNG format quite well.  UPNG.js is my own PNG decoder.  Adler CRC is stored for each PNG chunk (it is a part of PNG spec), bug  UPNG.js ignores it completely (CRC is computed only when encoding PNGs).

The PNG contains a big chunk of deflated data. So there is another Adler CRC in these data? How can I tell pako.js to skip it?

My image has 20 MPix, i.e. 80 MB. Having it in <img> + in Canvas + in ImageData at the same time is 240 MB of extra space. And I am not computing an overhead, that browsers have for each DOM structure. And you are right, Canvas does not support 16 bits per channel.  This issue should be about the inflate algorithm, not about PNGs.

**Comment by puzrin** [comment]
> The PNG contains a big chunk of deflated data. So there is another Adler CRC in these data? How can I tell pako.js to skip it?

There 3 possible data containers:

- Deflate RAW - just pure data.
- Deflate = [ header + deflate_raw + adlerCrc ]
- gzip = [ header + deflate_raw + crc32 ]

I don't know about png internals. But general principle is simple: if you have wrapped data - you can always decode header manually and execure InflateRaw over raw data block. Then crc will not be calculated.

PS. May be i'm wrong, and adler drop will give only 10% of benefit. 30% could be for crc32, it's more slow.

**Comment by desudesutalk** [comment]
@photopea in this case the only hope for you is either SIMD or WebAssembly. And when this technologies become common someone still need to rewrite pako for them.

**Comment by puzrin** [comment]
I theory, it's possible to split input stream for parallel run in webworkers. But, to be honest, i think that existing code is fast enougth, and it doesn't worth to spent time for improvements.

WASM is not as fast as people can imagine (if compared with properly optimized JS). We added wasm support into [pica](https://github.com/nodeca/pica) just for fun, to play with technolody. It became more stable, but real boost was only 25%.

**Comment by desudesutalk** [comment]
I don't think it is possible for pure JS to be as fast as native code. This is why we have WASM and SIMD. And WASM is too young for making any decisions about its profits.

**Comment by puzrin** [comment]
> I don't think it is possible for pure JS to be as fast as native code

You have benchmarks for js deflate, heavy computational task. It's only 1.6x slower than native code. That's good enougth in real world.

> This is why we have WASM and SIMD.

1. WASM is not about JS speed. It's about effective support of another languages/compilers in browser.
2. SIMD does not exists :) . Google already dropped drafts from chrome.

**Comment by desudesutalk** [comment]
> heavy computational task. It's only 1.6x slower than native code. 

*There is no such thing as "second place".*

Yes, for real world such results are very amazing. But when you do steganography/cryptography/compression/decompression in pure JS and all this in realtime on the live page and your browser (yes, Firefox, I'm talking about you!) freezes completely for several seconds when new image pops up, you start to dream about things which will make JS faster.

In real world you don't need fast JPEG codec in pure JS.

**Comment by puzrin** [comment]
In real world you speak about too general things when having concrete project with satisfying results :).

PS. js jpeg decoder is needed (and used) in pdf.js. It's also needed in any editor with 16bits channels support. And interface freezes can be avoided via webworkers use.

**Comment by photopea** [comment]
Let me tell you about my use case :)

I am developing the image editor www.Photopea.com . I believe it is the most advanced free image editor in the world (more complex than Gimp or Krita). And it is written completely in Javascript :)

Users decode and encode 10 MPx JPGs on a daily basis. They load PSD and Sketch files, that have hundreds of MBs, and require gigabytes of RAM after opening. I do computationally heavy image processing. Some algorithms work even [better than in Photoshop](https://blog.photopea.com/photopea-2-4.html). I implemented algorithms in JS, that have never been implemented in C or C++ (it can be a very new algorithm, and authors did their experiments e.g. in Matlab). So when somebody says "nobody would ever need this to be implemented in JS", I usually laugh :)

**Comment by puzrin** [comment]
@photopea my personal opinion, after writing fast JS (pako, pica, markdown/yaml parsers) is, that it is possible to do such things, but:

1. Not convenient.
2. With many limitations about math (int32 only, without division).

If i had to create fast and stable math now, i would look into WASM. There is experimental https://github.com/nodeca/multimath to play with universal and compact modules. But if you don't care about minimnal possible assets size, it will be more simple to use emscripten with their runtime.

**Comment by desudesutalk** [comment]
@puzrin 
> having concrete project with satisfying results :).

*Are we really talking about this in issue titled "Faster decompression"? :)*

> js jpeg decoder is needed (and used) in pdf.js

Very good point actually. This lib really looks like something what you can find on many sites around the internet. And what is more interesting - they use same lib as I do. And in theory I can backport my optimizations to pdf.js and make them something like 3 times faster in jpeg decoding. At least Huffman decoding will be faster and it looks like this is 3/4 of decoding time.

@photopea 
> Let me tell you about my use case :)

Very cool application, tbh. But it still differs from my case. Your app deals with files de/compression when user loads or saves his work. In this case additional 500ms of processing can be tolerated. But for my script there can be no idle times between image decompressions. And image parsing is only the half. Almost the same amount of time is needed for steganography and cryptography. And I can't use webworkers due to security. They are "unsafe territory" for my script (and this is "real" and not just "theoretical" attack vector). 

So it is me who needs fastest JPEG codec in pure JS. But my script and your photo editor are not jQuery or React. We will not find our scripts on half of the internet sites. Special cases are special cases. They exists but not needed everywhere.

@puzrin 
>If i had to create fast and stable math now, i would look into WASM. 

But *"WASM is not about JS speed. It's about effective support of another languages/compilers in browser."* :)

So yes, you right. This is what I'm talking about. I dream about something what allow me easily write fast code and use it in JS script. And it will be also nice if this thing will not be 1mb of mangled JS. But from the other hand, I was several times criticized for using Emscripten compiled/minified code - it is hard to audit.

Eh, it feels like I want to return again to my projects and continue them... :)

**Comment by photopea** [comment]
Hi guys. So instead of calling pako.inflate() starting at byte X,  I call pako.inflateRaw() starting at byte X+2. For my example, I got from 900 ms to 720 ms.

Can't you do it (skip CRC computation for inflate) by default? Now, in days of TCP and secure storages, I think that the corruption detection should be done on other "layers". Most of users are not familiar with ZLIB and they don't know they can skip the CRC part. There is no need to slow down your program by 20% for everybody, when the chance of corrupted data is almost zero.

**Comment by desudesutalk** [comment]
@photopea what if data was received over UDP? Or what if user upload corrupted file?

**Comment by puzrin** [comment]
> Can't you do it (skip CRC computation for inflate) by default?

No. This is no "my understanding how to do good inflate", this is port of standard library, it must have the same api.

**Comment by jimmykane** [comment]
<img width="312" alt="Screenshot 2019-12-25 at 19 28 44" src="https://user-images.githubusercontent.com/1268723/71449529-875a5d00-274e-11ea-8019-07b5a22ef715.png">
Wasm vs Pako on decode , gzip

**Comment by amw** [comment]
@jimmykane How did you make the comparison? Where did you get zlib implementation in WASM?
