### ISSUE TITLE
I dont understand what "pako" does or how it works, even after visiting your official website

### ISSUE THREAD

**Issue by heliosnarcissus** [nodeca/pako#191]
I randomly read about this on stackoverflow.
I dont understand how to use your library.
I have a website, I wanna make the size smaller so it loads faster. Pako is supposedly to aid in this endeavor. HOW?
Where are the guides? Where are the tutorials? Where are the Youtube and blog posts about Pako showing us how it's done?
Is this library for geniuses only?

**Comment by puzrin** [comment]
Sorry, can't help with generic programming questions.

May be, you could inspect dependent packages and see how those use pako https://www.npmjs.com/browse/depended/pako

**Comment by tomachinz** [comment]
I think lib is a lossless data compression library similar to ZIP, it would use RLE encoding (run length encoding). So that a piece of data like 111111111111111111110000000000000000000222222222222222222 could be sent more like 1(10)0(12)2(8) because runs repeats and patterns are put into a dictionary and referenced. I guess the more RAM you put into the dictionary the bigger the runs can be. I once compress a completely white million pixel TIFF file down from 1 megabyte to truly not much maybe 50kb was amazing. But the entire image was white.

**Comment by Directory** [comment]
@heliosnarcissus if you dont know what this does then its obviously not for you. pako is a js implementation of zlib. it will not make your site load faster. look into gzip and brotli. those are for implemented by the webserver such as nginx and handle compression on the request itself no programming required. this is for litteraly handling the inflation and deflation of bytes. you *could* at best use this to compress responses of api requests since thats the only thing you do. this is a js thing not an http thing like what gzip and brotli is.
