### ISSUE TITLE
Remove Z_SYNC_FLUSH from inflate

### ISSUE THREAD

**Issue by puzrin** [nodeca/pako#196]
zlib inflate does not use Z_SYNC_FLUSH anywhere (only deflate uses it).

Seems been added by mistake in #57.

Probably worth to completely revert that PR, because no tests exist and nobody know if that code works right.

**Comment by galuha** [comment]
Hello, guys!!!
Thanks for this amazing lib!!!
Btw, why did you removed this very useful feature. May be write tests for it?
It was not a mistake adding it.
For example, our server uses deflate instance for each websocket session. Each message is deflated and sent. Compression level this way is very high.
What is the workaround if one needs to inflate small msges on the client upon reception, maintaining the same inflate instance for the entire session?

**Comment by puzrin** [comment]
It was removed prior to wrapper rewrite, as not tested and difficult to maintain. I could NOT find any Z_SYNC_FLUSH constant use in inflate module. Probably, sync marks are flushed automatically.

I suggest to start with new wrapper, been done exactly as zlib manual recommends. Probably, it works as you need. If not - do PR again, but with test.

In worst case, you can create local wrapper in our code.

**Comment by galuha** [comment]
From zlib src files (from zib.net) zlib-1.2.11/inflate.c:
In this implementation, the flush parameter of inflate() only affects the
   return code (per zlib.h).  inflate() always writes as much as possible to
   strm->next_out, given the space available and the provided input--the effect
   documented in zlib.h of Z_SYNC_FLUSH.

It looks like this mode works automatically, as you have mentioned. So there should be no problem with testing, theoretically.  
Because of time constrains I'll stick to the older version of PAKO where Z_SYNC_FLUSH is still supported, for now. Maybe will do the PR with tests in the future.

Many thanks!

**Comment by puzrin** [comment]
https://github.com/nodeca/pako/blob/master/lib/deflate.js - this is wrapper around ported zlib code. It's quite small. But it's not trivial to make it universal for all possible use cases.

1. You can make PR with your cases + tests (then that will be maintainable and can be accepted)
2. You can replace wrapper to one from v1
3. You can stay at v1, because version bump was caused by wrapper rewrite. Low lever (zlib port) was not changed.
