### ISSUE TITLE
import { gzip } from "pako" no longer works

### ISSUE THREAD

**Issue by piotrblasiak** [nodeca/pako#202]
Not sure if it actually made any difference in terms of tree shaking etc, but with previous versions you could import just one function. For example, my js client uses pako for compressing requests and has no need for the inflate functions so would be great if it was possible to not import that - but perhaps that is not possible?

**Comment by puzrin** [comment]
I guess, that's a kind of your bundler emulation, because v1 had no modules support at all.

1. See `/dist` content. You can use es6 o es5 builds, and previous behaviour should be restored.
2. I'm not familiar with modules, and just used rollup to generate esm build. Any recommendations how to improve are welcome.

PS. Full rewrite to esm blocked by tests, which still need node v12.

**Comment by puzrin** [comment]
https://github.com/nodeca/pako/commit/d0382badcc60e1c08b51ea0aec10528e8565e1b6

Try v2.0.2. Should be fixed.

**Comment by piotrblasiak** [comment]
Fantastic. Thank you @puzrin
