### ISSUE TITLE
Return Promise?

### ISSUE THREAD

**Issue by jxu** [nodeca/pako#233]
If the use case is decompressing large files, then returning a Promise may be better than returning synchronously?

**Comment by puzrin** [comment]
Please avoid generic programming questions.

**Comment by jxu** [comment]
It is not a general programming question. It is a feature request

**Comment by puzrin** [comment]
That's not related to this package anyhow.

**Comment by jxu** [comment]
It has to do with the API, ex. how fetch API is implemented.

**Comment by rlidwka** [comment]
Pako works synchronously, it will block all JS execution for the duration of packing/unpacking, no matter what it would return.

*fetch API can't be a valid comparison here because it's API. They have to worry very much about future proofing because it'd be implemented by a huge number of browsers and libraries making it impossible to change later (and change in pako is no more severe than a major version bump).*
