### ISSUE TITLE
Using a predefined dictionary

### ISSUE THREAD

**Issue by omrio** [nodeca/pako#69]
Hello,

Kudos for the package :-)

I'd like to use it in my code, to compress many small JSON's, which share a lot of the strings (field names), but I'd like to compress each one separately (to be able to save memory and to access each one of them on demand without extracting the others).
I think a good solution for that would be to use a single predefined compression-dictionary, which is optimized for these JSON's and then the compression would be optimal for them.

Now, I saw that the readme file mentions that deflateSetDictionary, inflateSetDictionary and inflateGetDictionary are not supported by pako.

From what you know, how difficult should it be to add them to pako? Is there a special reason why they weren't implemented?

Thanks in advance,
Omri

**Comment by puzrin** [comment]
1. I think, implementation should not be very difficult, because all used components should be already available. It will be better if you dig sources yourself for such estimates. JS code is similar to original one.
2. We did not implemented it due time restrictions, and because we had no ideas where to apply and how to test it.

**Comment by puzrin** [comment]
Close as answered.

**Comment by IanYates** [comment]
If you're interested in compressing small bits of JSON you can also read this and go on from there to Ayende's other linked articles from within the post

https://ayende.com/blog/172865/reverse-engineering-the-smaz-compression-library

**Comment by diasdavid** [comment]
@puzrin would you consider reopening this issue? I'm working on getting this dictionaries working so that I can the spdy stream multiplexer ([spdy-transport](https://github.com/indutny/spdy-transport)) in the browser with [libp2p-spdy](https://github.com/diasdavid/js-libp2p-spdy). 

Started by implementing the dictionary tests available on Node.js core with pako API, https://github.com/diasdavid/pako/commit/a413b135036df5a7d01d31280389498da83762fc .

Since I'm not familiar with the code, getting it ready is taking more time than I initially expected, any word of advice or guidance would be extremely appreciated.

**Comment by puzrin** [comment]
@diasdavid TBH i'm not sure it's a good idea to put this feature into top-level API (very specific). Why not use those files directly https://github.com/nodeca/pako/tree/master/lib/zlib?

**Comment by puzrin** [comment]
`lib/zlib` has some [missed methods](https://github.com/nodeca/pako#notes), because we had no ideas how to use/test those, but PR will be accepted.

**Comment by diasdavid** [comment]
@puzrin seems like that in order to 'expose' them in the top-level API, they would have to be implemented first in `lib/zlib`. My goal is to be able to make [`browserify-zlib`](http://npmjs.org/browserify-zlib) to be able to shim completely the [Node.js zlib API](https://nodejs.org/api/zlib.html).

>  lib/zlib has some missed methods, because we had no ideas how to use/test those, but PR will be accepted.

For the ones respective to the dictionary, wouldn't using the same Node.js zlib tests help achieve reasonable guarantees?

**Comment by puzrin** [comment]
I don't know. Not familiar with it.

Anyway, i think it worth to start porting the rest to `lib/zlib` + add tests. That can be merger without problem. Then we can consider top-level api change, if that's really needed and useful.
